# Generated by Django 4.2.1 on 2023-05-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score_text',
            field=models.CharField(max_length=20),
        ),
    ]
